on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/setup-go@v5.0.0
        with:
          go-version: 1.21.3
      - uses: actions/checkout@v4
      - uses: imjasonh/setup-ko@v0.6
        env:
          KO_DOCKER_REPO: ghcr.io/kymppi/grafana-multitenant-auth

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and publish
        run: ko build . --bare --tags latest,${{ github.event.release.tag_name }}
